/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import repositorio.RepQuarto;
import repositorio.RepReserva;

/**
 *
 * @author dioge
 */
public class JFramePrincipal extends javax.swing.JFrame {

    RepQuarto repQuarto = new RepQuarto();
    RepReserva repReserva = new RepReserva();
    
    public JFramePrincipal() {
        initComponents();
        atualizaresumo();
    }
    
    public void atualizaresumo(){
        repQuarto.atulaizarativo();
        repQuarto.atulaizardesativoauto();
        jLabelLogado.setText("Bem vindo(a) "+Logar.logado);
        jLabelRservadas.setText(String.valueOf(repReserva.retornarTotalreservadas()));
        jLabelAtivas.setText(String.valueOf(repReserva.retornarTotalativas()));
        jLabelTHoje.setText(String.valueOf(repReserva.retornarTotalTerminamHoje()));
        jLabelDisponiveis.setText(String.valueOf(repQuarto.retornarTotalDisponivel()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabelRservadas = new javax.swing.JLabel();
        jLabelAtivas = new javax.swing.JLabel();
        jLabelTHoje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDisponiveis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelLogado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemFuncionarios = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemQuartos = new javax.swing.JMenuItem();
        jMenuReservas = new javax.swing.JMenu();
        jMenuINova = new javax.swing.JMenuItem();
        jMenuItemReservadas = new javax.swing.JMenuItem();
        jMenuItemAtivas = new javax.swing.JMenuItem();
        jMenuItemTerminamHoje = new javax.swing.JMenuItem();
        jMenuItemHistorico = new javax.swing.JMenuItem();
        jMenuQuartos = new javax.swing.JMenu();
        jMenuItemDisponiveis = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRservadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRservadas.setText("jLabel1");

        jLabelAtivas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAtivas.setText("jLabel2");

        jLabelTHoje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTHoje.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Reservadas:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ativas:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Terminam hoje:");

        jLabelDisponiveis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDisponiveis.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quartos Disponiveis:");

        jLabelLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogado.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Reservar!");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sino-do-hotel (2).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ocupado (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cronometros (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/abertura-da-porta-aberta (1).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/porta (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jMenuCadastrar.setText("Cadastros");

        jMenuItemFuncionarios.setText("Funcionários");
        jMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemFuncionarios);

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemClientes);

        jMenuItemQuartos.setText("Quartos");
        jMenuItemQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartosActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemQuartos);

        jMenuBar1.add(jMenuCadastrar);

        jMenuReservas.setText("Reservas");

        jMenuINova.setText("Nova Reserva");
        jMenuINova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuINovaActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuINova);

        jMenuItemReservadas.setText("Reservadas");
        jMenuItemReservadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservadasActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemReservadas);

        jMenuItemAtivas.setText("Ativas");
        jMenuItemAtivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtivasActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemAtivas);

        jMenuItemTerminamHoje.setText("Terminam Hoje");
        jMenuItemTerminamHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTerminamHojeActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemTerminamHoje);

        jMenuItemHistorico.setText("Histórico");
        jMenuItemHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoricoActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemHistorico);

        jMenuBar1.add(jMenuReservas);

        jMenuQuartos.setText("Quartos");

        jMenuItemDisponiveis.setText("Lista");
        jMenuItemDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisponiveisActionPerformed(evt);
            }
        });
        jMenuQuartos.add(jMenuItemDisponiveis);

        jMenuBar1.add(jMenuQuartos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(542, 542, 542)
                        .addComponent(jLabelLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6))
                                .addGap(218, 218, 218)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelDisponiveis))))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelLogado)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelRservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelTHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelAtivas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionariosActionPerformed
       chamarteLaCadastroFunci();
    }//GEN-LAST:event_jMenuItemFuncionariosActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
      chamarteLaCadastroCliente();
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartosActionPerformed
        chamarteLaQuartos();
    }//GEN-LAST:event_jMenuItemQuartosActionPerformed

    private void jMenuItemDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisponiveisActionPerformed
        chamarteLaQuartosDisponiveis();
    }//GEN-LAST:event_jMenuItemDisponiveisActionPerformed

    private void jMenuItemHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoActionPerformed
        chamarteLaHistoricoReservas();
    }//GEN-LAST:event_jMenuItemHistoricoActionPerformed

    private void jMenuINovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuINovaActionPerformed
        chamarteLaNovas();
    }//GEN-LAST:event_jMenuINovaActionPerformed

    private void jMenuItemReservadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservadasActionPerformed
        chamarteLaReservadas();
    }//GEN-LAST:event_jMenuItemReservadasActionPerformed

    private void jMenuItemAtivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtivasActionPerformed
        chamarteLaAtivas();
    }//GEN-LAST:event_jMenuItemAtivasActionPerformed

    private void jMenuItemTerminamHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTerminamHojeActionPerformed
        chamarteLaTerminamhoje();
    }//GEN-LAST:event_jMenuItemTerminamHojeActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        chamarteLaQuartosDisponiveis();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        chamarteLaReservadas();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        chamarteLaTerminamhoje();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        chamarteLaAtivas();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       chamarteLaNovas();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    
    public void chamarteLaTerminamhoje(){
        
        JDReservasFinalizamHoje jDReservasFinalizamHoje = new JDReservasFinalizamHoje (this, false);
        try{
            jDReservasFinalizamHoje.setModal(true);
            jDReservasFinalizamHoje.setVisible(true);
        }finally{
            jDReservasFinalizamHoje.dispose();
            atualizaresumo();
        }
    }
    
     public void chamarteLaAtivas(){
        
        JDReservasAtivas jDReservasAtivas = new JDReservasAtivas (this, false);
        try{
            jDReservasAtivas.setModal(true);
            jDReservasAtivas.setVisible(true);
        }finally{
            jDReservasAtivas.dispose();
            atualizaresumo();
        }
    }
    
    public void chamarteLaReservadas(){
        
        JDReservadas jDReservadas = new JDReservadas (this, false);
        try{
            jDReservadas.setModal(true);
            jDReservadas.setVisible(true);
        }finally{
            jDReservadas.dispose();
            atualizaresumo();
        }
    }
    
    public void chamarteLaQuartosDisponiveis(){
        
        JDQuartosDisponiveis jDQuartosdisponiveis= new JDQuartosDisponiveis(this, false);
        try{
            jDQuartosdisponiveis.setModal(true);
            jDQuartosdisponiveis.setVisible(true);
        }finally{
            jDQuartosdisponiveis.dispose();
            atualizaresumo();
        }
    }
    
    public void chamarteLaNovas(){
        
        JDReservar jDReservar= new JDReservar(this, false);
        try{
            jDReservar.setModal(true);
            jDReservar.setVisible(true);
        }finally{
            jDReservar.dispose();
            atualizaresumo();
        }
    }
    
    public void chamarteLaQuartos(){
        
        JDQuartos jDQuartos= new JDQuartos(this, false);
        try{
            jDQuartos.setModal(true);
            jDQuartos.setVisible(true);
        }finally{
            jDQuartos.dispose();
            atualizaresumo();
        }
    }
     public void chamarteLaHistoricoReservas(){
        
        JDHistoricoReservas jDhistorico= new JDHistoricoReservas(this, false);
        try{
            jDhistorico.setModal(true);
            jDhistorico.setVisible(true);
        }finally{
            jDhistorico.dispose();
            atualizaresumo();
        }
    }
    public void chamarteLaCadastroFunci(){
        
        JDCadastroFunci jDProdutos = new JDCadastroFunci(this, false);
        try{
            jDProdutos.setModal(true);
            jDProdutos.setVisible(true);
        }finally{
            jDProdutos.dispose();
            atualizaresumo();
        }
    }
    
    public void chamarteLaCadastroCliente(){
        
        JDClientes jDClientes = new JDClientes(this, false);
        try{
            jDClientes.setModal(true);
            jDClientes.setVisible(true);
        }finally{
            jDClientes.dispose();
            atualizaresumo();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAtivas;
    private javax.swing.JLabel jLabelDisponiveis;
    private javax.swing.JLabel jLabelLogado;
    private javax.swing.JLabel jLabelRservadas;
    private javax.swing.JLabel jLabelTHoje;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuINova;
    private javax.swing.JMenuItem jMenuItemAtivas;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemDisponiveis;
    private javax.swing.JMenuItem jMenuItemFuncionarios;
    private javax.swing.JMenuItem jMenuItemHistorico;
    private javax.swing.JMenuItem jMenuItemQuartos;
    private javax.swing.JMenuItem jMenuItemReservadas;
    private javax.swing.JMenuItem jMenuItemTerminamHoje;
    private javax.swing.JMenu jMenuQuartos;
    private javax.swing.JMenu jMenuReservas;
    // End of variables declaration//GEN-END:variables
}
